import React from 'react';

import { ReactComponent as Icon1 } from './plus.svg';
import { ReactComponent as Icon2 } from './chevron-left.svg';
import { ReactComponent as Icon3 } from './chevron-right.svg';
import { ReactComponent as Icon4 } from './microphone.svg';
import { ReactComponent as Icon5 } from './nav-menu-button.svg';
import { ReactComponent as Icon6 } from './notification.svg';
import { ReactComponent as Icon7 } from './settings.svg';
import { ReactComponent as Icon8 } from './arrow-left.svg';
import { ReactComponent as Icon9 } from './arrow-right.svg';
import { ReactComponent as Icon10 } from './x-close-big.svg';
import { ReactComponent as Icon11 } from './x-close.svg';
import { ReactComponent as Icon12 } from './calendar.svg';
import { ReactComponent as Icon13 } from './clock.svg';
import { ReactComponent as Icon14 } from './bell.svg';
import { ReactComponent as Icon15 } from './logo.svg';
import { ReactComponent as Icon16 } from './no-todo.svg';

export const PlusIcon = React.memo(Icon1);
export const ChevronLeftIcon = React.memo(Icon2);
export const ChevronRightIcon = React.memo(Icon3);
export const MicrophoneIcon = React.memo(Icon4);
export const NavMenuIcon = React.memo(Icon5);
export const NotificationIcon = React.memo(Icon6);
export const SettingsIcon = React.memo(Icon7);
export const ArrowLeftIcon = React.memo(Icon8);
export const ArrowRightIcon = React.memo(Icon9);
export const CloseXBigIcon = React.memo(Icon10);
export const CloseXSmallIcon = React.memo(Icon11);
export const CalenderIcon = React.memo(Icon12);
export const ClockIcon = React.memo(Icon13);
export const BellIcon = React.memo(Icon14);
export const LogoMobile = React.memo(Icon15);
export const NoTodoData = React.memo(Icon16);
